_target_: dataloading.osteosarcomaDataModule.OsteosarcomaDataModule
batch_size: 8
train_val_ratio: 0.7
base_path: # Set this to the path containing the Osteosarcoma data from UT Southwestern/UT Dallas https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=52756935
num_workers: 12
img_size:
  - 512
  - 512
n_splits: ${n_folds}
