defaults:
  - model: efficientnetb0
  - optimizer: adam
  - scheduler: cosine
  - datamodule: osteosarcoma
  - _self_

experiment_name: osteosarcoma
run_name: ${model.name}
n_folds: 1
pretrained: True

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  max_epochs: 100
  log_every_n_steps: 50
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: epoch

criterion:
  _target_: torch.nn.CrossEntropyLoss

num_classes: 3
